Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hkokim0309

  jpa:
    hibernate:
      ddl-auto: update

auth:
  jwt:
    secret: 7J2M7JWE66y06rKD64+E7ZWY6riw7Iur7J2A7J2064qQ64KM66y07Iqo64qQ64KM7J247KeA6reA7LCu64Sk
    access_exp: 8640
    refresh_exp: 86400
    header: Authorization
    prefix: Bearer
